#!/bin/sh
# shellcheck disable=SC1090

[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

systemctl --user import-environment DISPLAY
WALLPAPER=$HOME/Pictures/wallpaper.jpg
SKIP_PRE=0

prewm() {
    [ "$SKIP_PRE" = 1 ] && return

    pgrep -x fcitx5 || fcitx5 -d > /dev/null 2>&1
    pgrep -x dxhd || dxhd > /dev/null 2>&1 &
    pgrep -x redshift || redshift > /dev/null 2>&1 &
    pgrep -x polkit-gnome-authentication-agent-1 || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 > /dev/null 2>&1 &

    prede
}

prede() {
    [ "$SKIP_PRE" = 1 ] && return

    pgrep -x tym || tym --daemon > /dev/null 2>&1 &
    libinput-gestures-setup restart > /dev/null 2>&1 &
}

startdwm() {
    pgrep -x xwallpaper || xwallpaper --zoom "$WALLPAPER" --daemon
    pgrep -f statusd || statusd &
    exec dwm
}

startgnome() {
    export GTK_CSD=1
    export XDG_SESSION_TYPE=x11
    export GDK_BACKEND=x11
    exec gnome-session
}

WM=${1:-dwm}

if [ "${WM%2x}" != "$WM" ]; then
    export XCURSOR_SIZE=48
    export GDK_SCALE=2
    export GDK_DPI_SCALE=0.6
    export QT_AUTO_SCREEN_SCALE_FACTOR=0
    {   echo "Xft.dpi: 144"
        echo "Xcursor.size: 48"
        echo "xmenu.height: 48"
        echo "dwm.borderpx: 4"
        echo "dwm.barheight: 48"
        echo "dmenu.minheight: 48"
    } > /tmp/Xresources.Xft.dpi
    xrdb -merge /tmp/Xresources.Xft.dpi
else
    {   echo "Xft.dpi: 96"
        echo "Xcursor.size: 36"
        echo "xmenu.height: 36"
        echo "dwm.borderpx: 3"
        echo "dwm.barheight: 36"
        echo "dmenu.minheight: 36"
    } > /tmp/Xresources.Xft.dpi
    xrdb -merge /tmp/Xresources.Xft.dpi
fi

if [ "${WM%simp}" = "$WM" ]; then
    SKIP_PRE=1
fi

case "$WM" in
    awesome*) prewm; exec awesome;;
    dwm*) prewm; startdwm;;
    gnome*) prede; startgnome;;
    *) exec "$@";;
esac
