## This config is used in the fbtmux script, better to use in fbterm (with support for more fonts)

# As in the fbtmux script, I recommand start a tmux session with a
# special session name, e.g. fbtmux, and a special socket name, e.g. fbtmux
# so that only this session uses the config and the normal sessions remain
# unaffected.
# e.g.
# tmux -L fbtmux -f .fbtmux.conf new -A -s fbtmux

## Source the common configs
MAIN_CONF="$HOME/.config/tmux/tmux.conf"
FBTMUX_CONF="$HOME/.config/tmux/fbtmux.conf"
source $MAIN_CONF
bind r source-file $FBTMUX_CONF

## Multimedia
# Change brightness
bind -N "Turn down brightness" -n M-_ display "statusc light down"
bind -N "Turn up brightness"   -n M-+ display "statusc light up"
# Change volume
bind -N "Turn down volume" -n M-\{ display "statusc vol down"
bind -N "Turn up volume"   -n M-\} display "statusc vol up"
bind -N "Toggle volume"    -n M-| display "statusc vol toggle"

# Screenshot
bind -N "Take screenshot" -n M-s run -b "fbgrab ~/Pictures/FrameBuffer_$(date +%F_%H-%M-%S).png"

# vim: ft=tmux
