[lint]
select = [
    "ALL"
]
ignore = [
    "ERA",    # eradicate, for commented-out code
    "ANN",    # flake8-annotations, type hints
    "FIX",    # flake8-fixme, todos
    "T20",    # flake8-print, no prints
    "Q",      # flake8-quotes, single or double
    "TD",     # flake8-todos, todos
    "PTH",    # flake8-use-pathlib, os -> pathlib
    "RET504", # flakt8-return, unnecessary assignment before return
    "EM",     # flake8-errmsgs, no strings in exceptions
    "PLR",    # Pylint refactors
    "TRY003", # tryceratops, messages in exceptions
]

[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
"**/tests/*.py" = [
    "S101",
    "INP001",
]
