#!/usr/bin/env python

import atexit
import os
import readline

histfile = os.path.join(os.getenv("XDG_DATA_HOME"), "python_history")

try:
    readline.read_history_file(histfile)
except FileNotFoundError:
    open(histfile, 'wb').close()

readline.set_history_length(1000)
atexit.register(readline.write_history_file, histfile)
