XDG_CONFIG_HOME=$HOME/.config
XDG_CACHE_HOME=$HOME/.cache
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state
XDG_RUNTIME_DIR=/run/user/$USERID
XDG_DATA_DIRS=/usr/share:/usr/local/share
XDG_CONFIG_DIRS=/etc/xdg
