"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
palette = "default"
format = """
[░▒▓](          fg:color1)\
[  ](          fg:color7 bg:color1)\
[](            fg:color1 bg:color2)\
[$directory](   fg:color0 bg:color2 bold)\
[](            fg:color2 bg:color4)\
[$git_branch](  fg:color1 bg:color4)\
[$git_state](   fg:color1 bg:color4)\
[$git_status](  fg:color1 bg:color4)\
[](            fg:color4 bg:color5)\
[$c](           fg:color2 bg:color5)\
[$lua](         fg:color2 bg:color5)\
[$python](      fg:color2 bg:color5)\
[$package](     fg:color2 bg:color5)\
[](            fg:color5 bg:color6)\
[$cmd_duration](fg:color3 bg:color6)\
[$jobs](        fg:color3 bg:color6)\
[$env_var](     fg:color3 bg:color6)\
[](            fg:color6)\
\n$character"""

[palettes.default]
color0 = "#ffffff"
color1 = "#c0caf5"
color2 = "#9aa5ce"
color3 = "#565f89"
color4 = "#394260"
color5 = "#292e42"
color6 = "#1d2230"
color7 = "#090c0c"

[c]
symbol = " "
format = ' $symbol$name:$version '

[lua]
symbol = " "
format = ' $symbol$version '

[python]
symbol = " "
format = " ${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )"

[cmd_duration]
min_time = 500
show_milliseconds = true
format = " $duration "

[directory]
format = " $path "
truncation_length = 1
truncation_symbol = ""

[git_branch]
symbol = " "
format = ' $symbol$branch '

[git_state]
format = "\\($state( $progress_current/$progress_total)\\) "

[git_status]
format = '($all_status$ahead_behind )'

[jobs]
format = " $symbol$number "

[package]
symbol = " "
format = " $symbol$version "
