#!/bin/sh

HOME=${HOME%%/}
# PATH
for p in "$HOME/.gem/ruby" "$HOME/.local/bin" "$HOME/.local/share/npm/bin"; do
    if [ -d "$p" ] && [ "$PATH" = "${PATH%$p*}" ]; then
        export PATH="$p:${PATH}"
    fi
done

# Environments
export EDITOR=vim
export VISUAL=vim
export NOTES_DIRECTORY="$HOME/Code/notes"
export FBFONT="/usr/share/kbd/consolefonts/ter-216n.psf.gz"

# XDG base directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export LESSHISTFILE=-
export ELINKS_CONFDIR="$XDG_CONFIG_HOME/elinks"
export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/ipython"
export MATHEMATICA_USERBASE="$XDG_CONFIG_HOME/Mathematica"
export PASSWORD_STORE_DIR="$XDG_CONFIG_HOME/password-store"
export MPLAYER_HOME="$XDG_CONFIG_HOME/mplayer"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export GRIPHOME="$XDG_CONFIG_HOME/grip"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"
export ABDUCO_SOCKET_DIR="$XDG_RUNTIME_DIR"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME/bundle"
export DVDCSS_CACHE="$XDG_DATA_HOME/dvdcss"
export MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
export MYGVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
export EXINIT=":source $XDG_CONFIG_HOME/ex/exrc"
export VIMINIT=":source $MYVIMRC"
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export RANDFILE="$XDG_CACHE_HOME/openssl_rnd"

export LYNX_CFG="$XDG_CONFIG_HOME/lynx/lynx.cfg"
export LYNX_LSS="$XDG_CONFIG_HOME/lynx/lynx.lss"

# Set icons in lf
export LF_ICONS="\
.git=󰊢:\
Desktop=󰇄:\
Documents=󰠮:\
Downloads=󰉍:\
Dotfiles=󰇣:\
Dropbox=󰇣:\
Music=󱍙:\
Pictures=󰉏:\
Public=󰀎:\
Templates=󱔗:\
Videos=󰕧:\
*.1=󰞋:\
*.7z=󰀼:\
*.7z=󰗄:\
*.a=󰌱:\
*.aac=󰈟:\
*.ace=󰗄:\
*.ai=󱇣:\
*.alz=󰗄:\
*.apk=󰀼:\
*.arc=󰗄:\
*.arj=󰗄:\
*.asf=󰈟:\
*.asm=󰌜:\
*.asp=󰖟:\
*.au=󰈟:\
*.aup=󰈣:\
*.avi=󰷝:\
*.avi=󰈟:\
*.bash=󰆍:\
*.bat=󰒓:\
*.bmp=󰈟:\
*.bmp=󰈟:\
*.bz2=󰗄:\
*.bz=󰗄:\
*.c++=󰙲:\
*.c=󰙱:\
*.cab=󰗄:\
*.cbr=󱓷:\
*.cbz=󱓷:\
*.cc=󰙲:\
*.cgm=󰈟:\
*.class=󰬷:\
*.clj=󰈮:\
*.clj=󰈮:\
*.cljc=󰈮:\
*.cljs=󰈮:\
*.cmake=󰌱:\
*.cmd=󰆍:\
*.coffee=󰅶:\
*.conf=󰒓:\
*.cp=󰙲:\
*.cpio=󰀼:\
*.cpio=󰗄:\
*.cpp=󰙲:\
*.cs=󰌛:\
*.css=󰌜:\
*.cue=󰈣:\
*.cvs=󰒓:\
*.cxx=󰙲:\
*.d=󰈮:\
*.dart=󰈮:\
*.db=󰆼:\
*.deb=󰀼:\
*.diff=󰢪:\
*.dl=󰈟:\
*.dll=󰖳:\
*.doc=󰈬:\
*.docx=󰈬:\
*.dump=󰆼:\
*.dwm=󰗄:\
*.dz=󰗄:\
*.ear=󰗄:\
*.efi=󰈮:\
*.ejs=󰌝:\
*.elf=󰈮:\
*.emf=󰈟:\
*.epub=󰈬:\
*.erl=󰈮:\
*.esd=󰗄:\
*.exe=󰖳:\
*.f#=󰈮:\
*.fifo=󰟦:\
*.fish=󰈮:\
*.flac=󰈣:\
*.flc=󰈟:\
*.fli=󰈟:\
*.flv=󰷝:\
*.fs=󰈮:\
*.fs=󰈮:\
*.fsi=󰈮:\
*.fsscript=󰈮:\
*.fsx=󰈮:\
*.gem=󰀼:\
*.gif=󰈟:\
*.gitignore=󰊢:\
*.gl=󰈟:\
*.go=󰟓:\
*.gz=󰗄:\
*.gzip=󰗄:\
*.h=󰙱:\
*.hbs=󰈮:\
*.hh=󰙲:\
*.hpp=󰙲:\
*.hs=󰲒:\
*.htaccess=󰒓:\
*.htm=󰌝:\
*.html=󰌝:\
*.htpasswd=󰒓:\
*.ico=󰈟:\
*.img=󰗮:\
*.ini=󰒓:\
*.iso=󰗮:\
*.jar=󰬷:\
*.java=󰬷:\
*.java=󰬷:\
*.jl=󰌱:\
*.jpeg=󰈟:\
*.jpg=󰈟:\
*.js=󰌞:\
*.js=󰌞:\
*.json=󰘦:\
*.jsx=󱀤:\
*.key=󱕴:\
*.less=󰌜:\
*.lha=󰀼:\
*.lhs=󰲒:\
*.log=󰺄:\
*.lrz=󰗄:\
*.lua=󰢱:\
*.lz4=󰗄:\
*.lz=󰗄:\
*.lzh=󰗄:\
*.lzma=󰗄:\
*.lzo=󰗄:\
*.m2v=󰈟:\
*.m4a=󰈣:\
*.m4v=󰷝:\
*.markdown=󰍔:\
*.md=󰍔:\
*.mid=󰈟:\
*.midi=󰈟:\
*.mjpeg=󰈟:\
*.mjpg=󰈟:\
*.mka=󰈟:\
*.mkv=󰷝:\
*.ml=󰈮:\
*.mli=󰈮:\
*.mng=󰈟:\
*.mov=󰷝:\
*.mp3=󰈣:\
*.mp4=󰷝:\
*.mp4v=󰈟:\
*.mpc=󰈟:\
*.mpeg=󰷝:\
*.mpg=󰷝:\
*.msi=󰖳:\
*.mustache=󰈮:\
*.nix=󱄅:\
*.nuv=󰈟:\
*.o=󰌱:\
*.oga=󰈟:\
*.ogg=󰈣:\
*.ogm=󰈟:\
*.ogv=󰈟:\
*.ogx=󰈟:\
*.opus=󰈟:\
*.pbm=󰈟:\
*.pcx=󰈟:\
*.pdf=󰈥:\
*.pgm=󰈟:\
*.php=󰌟:\
*.php=󰌟:\
*.pl=󰈮:\
*.pl=󰈮:\
*.pm=󰈮:\
*.png=󰈟:\
*.ppm=󰈟:\
*.ppt=󰈟:\
*.pptx=󰈟:\
*.pro=󰏒:\
*.ps1=󰆍:\
*.psb=󱇣:\
*.psd=󱇣:\
*.pub=󱕴:\
*.py=󰌠:\
*.py=󰌠:\
*.pyc=󰌠:\
*.pyd=󰌠:\
*.pyo=󰌠:\
*.qt=󰈟:\
*.ra=󰈟:\
*.rar=󰀼:\
*.rar=󰗄:\
*.rb=󰴭:\
*.rb=󰴭:\
*.rc=󰒓:\
*.rlib=󱘗:\
*.rm=󰈟:\
*.rmvb=󰈟:\
*.rom=󰈮:\
*.rpm=󰀼:\
*.rpm=󰗄:\
*.rs=󱘗:\
*.rs=󱘗:\
*.rss=󰑫:\
*.rtf=󰈬:\
*.rz=󰗄:\
*.s=󰌜:\
*.sar=󰗄:\
*.scala=󰈮:\
*.scala=󰈮:\
*.scss=󰌜:\
*.sh=󰌜:\
*.sh=󰆍:\
*.slim=󰌝:\
*.sln=󰘐:\
*.so=󰌱:\
*.spx=󰈟:\
*.sql=󰆼:\
*.styl=󰌜:\
*.suo=󰘐:\
*.svg=󰈟:\
*.svgz=󰈟:\
*.swm=󰗄:\
*.t7z=󰗄:\
*.t=󰈮:\
*.tar=󰀼:\
*.tar=󰗄:\
*.taz=󰗄:\
*.tbz2=󰗄:\
*.tbz=󰗄:\
*.tga=󰈟:\
*.tgz=󰀼:\
*.tgz=󰗄:\
*.tif=󰈟:\
*.tiff=󰈟:\
*.tlz=󰗄:\
*.ts=󰛦:\
*.ts=󰛦:\
*.twig=󰌟:\
*.txz=󰗄:\
*.tz=󰗄:\
*.tzo=󰗄:\
*.tzst=󰗄:\
*.vim=󰒓:\
*.viminfo=󰒓:\
*.vimrc=󰒓:\
*.vob=󰈟:\
*.war=󰗄:\
*.wav=󰈣:\
*.webm=󰷝:\
*.wim=󰗄:\
*.wmv=󰈟:\
*.xbm=󰈟:\
*.xbps=󰀼:\
*.xcf=󰈟:\
*.xhtml=󰌝:\
*.xls=󰈛:\
*.xlsx=󰈛:\
*.xml=󰗀:\
*.xpm=󰈟:\
*.xspf=󰈟:\
*.xul=󰈹:\
*.xwd=󰈟:\
*.xz=󰀼:\
*.xz=󰗄:\
*.yaml=󰒓:\
*.yml=󰒓:\
*.yuv=󰈟:\
*.z=󰗄:\
*.zip=󰗄:\
*.zoo=󰗄:\
*.zsh=󰆍:\
*.zst=󰗄:\
di=󰉋:\
ex=󰑣:\
fi=󰎞:\
ln=󱅷:\
or=󱅷:\
"
